server:
  port: 8080
spring:
  application:
    name: mybatis-plus-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: chenys
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10 #\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5\u6570
      maximum-pool-size: 20 #\u6700\u5927\u8FDE\u63A5\u6C60\u6570\u91CF
      auto-commit: true # \u5F00\u542F\u81EA\u52A8\u8FDE\u63A5
mybatis-plus:
  type-enums-package: com.chenys.mybatisplus.entity.enums # \u914D\u7F6E\u626B\u63CF\u901A\u7528\u679A\u4E3E
  mapper-locations: classpath:/mapper/*Mapper.xml
  #\u5B9E\u4F53\u626B\u63CF\uFF0C\u591A\u4E2Apackage\u7528\u9017\u53F7\u6216\u8005\u5206\u53F7\u5206\u9694
  typeAliasesPackage: com.chenys.mybatisplus.entity
  global-config:
    db-config:
      logic-delete-field: deleted  # \u5168\u5C40\u903B\u8F91\u5220\u9664\u7684\u5B9E\u4F53\u5B57\u6BB5\u540D(since 3.3.0,\u914D\u7F6E\u540E\u53EF\u4EE5\u5FFD\u7565\u4E0D\u914D\u7F6E\u6B65\u9AA42)
      logic-delete-value: 1 # \u903B\u8F91\u5DF2\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 1)
      logic-not-delete-value: 0 # \u903B\u8F91\u672A\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 0)
  configuration:
    # \u63A7\u5236\u53F0\u6253\u5370SQL\u8BED\u53E5
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
